apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-service-account
  namespace: welcome
secrets:
- name: dockerhub-creds
imagePullSecrets:
- name: dockerhub-creds
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: cluster-store
  namespace: welcome
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/full
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
  namespace: welcome
spec:
  id: "io.buildpacks.stacks.jammy-tiny"
  buildImage:
    image: "paketobuildpacks/build-jammy-tiny-stack"
  runImage:
    image: "paketobuildpacks/run-jammy-tiny-stack"
---
apiVersion: kpack.io/v1alpha2
kind: ClusterLifecycle
metadata:
  name: default-lifecycle
  namespace: welcome
spec:
  image: buildpacksio/lifecycle
---
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: my-builder
  namespace: welcome
spec:
  serviceAccountName: docker-service-account
  tag: latest
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/full