name: Build Hugo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Hugo
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y hugo
          hugo version
        
      - name: Build Hugo
        run: |
          hugo build