name: Build Hugo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      
      - name: Setup Hugo
        run: |
          sudo apt-get update -y 
          sudo apt-get install -y git
          go install github.com/gohugoio/hugo@latest
        
      - name: Building
        run: |
          cd hello-world
          ls -l
          hugo --config hugo.toml
          hugo --destination public

      - name: check pwd
        run: |
          cd hello-world
          ls -l
          pwd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-public
          path: hello-world/public/

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-public
      
      - name: List files
        run: |
          ls -l
          pwd
